### ISSUE TITLE
License of withed unit "GNATCOLL.Refcount" may be inconsistent.

### ISSUE THREAD

**Issue by Blady-Com** [AdaCore/libadalang-tools#4]
Hello,

I've the following issue with libadalang:
```
[Ada] langkit_support-tree_traversal_iterator.adb
langkit_support-tree_traversal_iterator.ads:24:14: warning: license of withed unit "GNATCOLL.Refcount" may be inconsistent
compilation of langkit_support-tree_traversal_iterator.adb failed
```
Is there a way to avoid warning processed as errors?
Maybe manage.py might support --gpr-opts as GnatColl do.

My configuration: GNAT Community 2019 on macOS 10.13.6.

Thanks, Pascal.

**Comment by pmderodat** [comment]
Hello Pascal,

Note that your request is about Libadalang, so the appropriate place to open this issue was https://github.com/AdaCore/libadalang/issues/

Build in production mode (`--build-mode=prod`) to avoid warning as errors. Alternatively, in order to get rid of this warning, you can rebuild XML/Ada, LibGPR and GNATcoll from GitHub sources (so that licenses are consistent).
